name: Deploy portfolio

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 2.1: Checkout repo
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2.2: Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    # Step 2.3: Install dependencies & build
    - name: Install & Build
      run: |
        npm install
        npm run build

    # Step 2.4: Deploy to EC2 via SSH
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SECRET_KEY }}
        port: 22
        script: |
          set -e
          cd /home/ubuntu/portfolio
          git reset --hard
          git pull origin master
          npm install --production
          pm2 restart portfolio || pm2 start npm --name portfolio -- start
          pm2 save
