name: Deploy Portfolio

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest   # GitHub cloud runner
    outputs:
      artifact-path: ${{ steps.build.outputs.artifact-path }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install & Build
        id: build
        run: |
          npm ci
          npm run build
          echo "artifact-path=.next" >> $GITHUB_OUTPUT

      - name: Upload production build
        uses: actions/upload-artifact@v3
        with:
          name: next-build
          path: |
            .next
            package.json
            package-lock.json
            public
            next.config.js

  deploy:
    runs-on: self-hosted     # Your EC2 runner
    needs: build             # wait until build finishes
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: next-build
          path: /home/ubuntu/portfolio

      - name: Install production deps
        run: |
          cd /home/ubuntu/portfolio
          npm ci --omit=dev

      - name: Restart with PM2
        run: |
          pm2 restart portfolio || pm2 start npm --name portfolio -- start
          pm2 save
