name: Deploy Portfolio

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install & Build
        run: |
          npm ci                # install all deps including dev (for TypeScript)
          npm run build         

      # Upload standalone server, required inner .next, static files, and public folder
      - name: Upload production build
        uses: actions/upload-artifact@v4
        with:
          name: next-build
          path: |
            .next/standalone
            .next/standalone/.next   # ✅ inner .next (BUILD_ID etc.)
            .next/static
            public

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: next-build
          path: /home/ubuntu/portfolio

      # Restart PM2 using the prebuilt standalone server
      - name: Restart with PM2
        run: |
          cd /home/ubuntu/portfolio/.next/standalone
          pm2 delete portfolio || true
          pm2 start server.js --name portfolio
          pm2 save
