name: Deploy Portfolio

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest   # GitHub cloud runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install & Build
        run: |
          npm ci
          npm run build

      - name: Upload production build
        uses: actions/upload-artifact@v4
        with:
          name: next-build
          path: |
            .next/standalone
            .next/static
            public

  deploy:
    runs-on: self-hosted     # Your EC2 runner
    needs: build             # wait until build finishes

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: next-build
          path: /home/ubuntu/portfolio

      - name: Restart with PM2
        run: |
          cd /home/ubuntu/portfolio
          pm2 restart portfolio || pm2 start node --name portfolio .next/standalone/server.js
          pm2 save
