name: Deploy Portfolio

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest   # GitHub cloud runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install & Build
        run: |
          npm ci        # install only production deps
          npm run build

      # Upload the standalone server, static assets, and node_modules
      - name: Upload production build
        uses: actions/upload-artifact@v4
        with:
          name: next-build
          path: |
            .next/standalone
            .next/static
            public
            package.json
            package-lock.json
            .next/standalone/node_modules   # ✅ pre-installed modules

  deploy:
    runs-on: self-hosted     # Your EC2 runner
    needs: build             # wait until build finishes

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: next-build
          path: /home/ubuntu/portfolio

      # No installation needed on EC2
      # Just start/restart PM2 with prebuilt server
      - name: Restart with PM2
        run: |
          cd /home/ubuntu/portfolio/.next/standalone
          pm2 delete portfolio || true
          pm2 start server.js --name portfolio
          pm2 save
